dbt_ldif:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: "{{ env_var('DBT_POSTGRES_USER', 'postgres') }}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD', 'password') }}"
      port: 5432
      dbname: "{{ env_var('DBT_POSTGRES_DATABASE', 'ldif_analytics') }}"
      schema: "{{ env_var('DBT_POSTGRES_SCHEMA', 'ldif_dev') }}"
      threads: 4
      keepalives_idle: 0
      search_path: "{{ env_var('DBT_POSTGRES_SEARCH_PATH', 'public') }}"
    
    prod:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('DBT_POSTGRES_USER', 'postgres') }}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      port: "{{ env_var('DBT_POSTGRES_PORT', 5432) | as_number }}"
      dbname: "{{ env_var('DBT_POSTGRES_DATABASE', 'ldif_analytics') }}"
      schema: "{{ env_var('DBT_POSTGRES_SCHEMA', 'ldif_prod') }}"
      threads: 8
      keepalives_idle: 0
      search_path: "{{ env_var('DBT_POSTGRES_SEARCH_PATH', 'public') }}"